spring: 
    profiles: 
      active: 
      - dev
---
spring:
    profiles: dev     #开发环境
    application: 
        name: microservicecloud-config-wdc-dev
---
spring:
    profiles: test     #测试环境
    application: 
        name: microservicecloud-config-wdc-test

#一定要保存为 utf-8 格式